languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Gabriela Junqueira"
#logo = "img/diatom_logo.png"
description = "My personal website"
copyright = "&copy; 2023 Gabriela Junqueira"

dateFormat = "2 January 2006"

[author]
  name = "Gabriela Junqueira"
  image = "img/gabriela.png"
  headline = "Ph.D. Candidate in Ecology"
  bio = "Ecology . Data Visualization"
  links = [
     { email = "mgjn.junqueira@gmail.com" },
     { github = "https://github.com/junqueiragaabi" },
     { twitter = "https://twitter.com/junqueiragaabi" }
  ]